# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: zbelzer.github.com
title: "Belzer's Blog"
author: Zachary Belzer
email: zbelzer@gmail.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-21759057-1

github:
  username: zbelzer

# disqus:
#   id: disqusid
